/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./app/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        navy: "var(--navy)",
        "navy-light": "var(--navy-light)",
        neon: "var(--neon)",
        amber: "var(--amber)",
        violet: "var(--violet)",
        "navy-dark": "hsl(228 70% 3%)",
        "navy-foreground": "hsl(0 0% 100%)",
        "muted-foreground-subtle": "hsl(210 20% 80%)",
      },
      fontFamily: {
        sans: ["Barlow", "ui-sans-serif", "system-ui", "sans-serif"],
        heading: ["Barlow", "sans-serif"],
        body: ["Barlow", "sans-serif"],
        display: ["Archivo Black", "Barlow", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        medium: "calc(var(--radius) - 2px",
        sm: "calc(var(--radius) - 4px",
      },
      boxShadow: {
        neon: "0 0 24px -6px rgba(0,240,255,0.7)",
        "neon-sm": "0 0 14px -6px rgba(0,240,255,0.55)",
      },
    },
    colors: {
      light: {
        background: "hsl(228 64% 5%)",
        foreground: "hsl(0 0% 100%)",
        card: "hsl(228 58% 7%)",
        "card-foreground": "hsl(0 0% 100%)",
        primary: "hsl(189 100% 50%)",
        "primary-foreground": "hsl(228 70% 6%)",
        secondary: "hsl(45 100% 53%)",
        "secondary-foreground": "hsl(228 70% 6%)",
        muted: "hsl(228 50% 10%)",
        "muted-foreground": "hsl(190 28% 75%)",
        accent: "hsl(189 95% 55%)",
        "accent-foreground": "hsl(228 70% 6%)",
        destructive: "hsl(0 84% 60%)",
        "destructive-foreground": "hsl(0 0% 100%)",
        border: "hsl(189 80% 55% / 0.18)",
        input: "hsl(189 80% 55% / 0.22)",
        ring: "hsl(189 100% 52%)",
      },
      dark: {
        background: "hsl(228 64% 3%)",
        foreground: "hsl(0 0% 100%)",
        card: "hsl(228 58% 7%)",
        "card-foreground": "hsl(0 0% 100%)",
        primary: "hsl(189 100% 50%)",
        "primary-foreground": "hsl(228 70% 6%)",
        secondary: "hsl(45 100% 53%)",
        "secondary-foreground": "hsl(228 70% 6%)",
        muted: "hsl(228 50% 10%)",
        "muted-foreground": "hsl(210 20% 80%)",
        accent: "hsl(189 95% 55%)",
        "accent-foreground": "hsl(228 70% 6%)",
        destructive: "hsl(0 84% 60%)",
        "destructive-foreground": "hsl(0 0% 100%)",
        border: "hsl(189 80% 55% / 0.35)",
        input: "hsl(189 80% 55% / 0.35)",
        ring: "hsl(189 100% 52%)",
      },
    },
  },
  plugins: [],
};